#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME, XARGS.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -B 0 -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
: ${XARGS:=/usr/bin/xargs}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $DIRNAME "$2" | $XARGS $MKDIR -p
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $DIRNAME "$2" | $XARGS $MKDIR -p
  $LN -sf "$1" "$2"
}
handle_file_ln "/home/denis/.dotfiles/bashrc" "/home/denis/.bashrc"
handle_file_ln "/home/denis/.dotfiles/config/awesome/rc.lua" "/home/denis/.config/awesome/rc.lua"
handle_file_ln "/home/denis/.dotfiles/install.sh" "/home/denis/.install.sh"
handle_file_ln "/home/denis/.dotfiles/LICENSE" "/home/denis/.LICENSE"
handle_file_ln "/home/denis/.dotfiles/rcrc" "/home/denis/.rcrc"
handle_file_ln "/home/denis/.dotfiles/README.md" "/home/denis/.README.md"
handle_file_ln "/home/denis/.dotfiles/ssh/config" "/home/denis/.ssh/config"
handle_file_ln "/home/denis/.dotfiles/tags" "/home/denis/.tags"
handle_file_ln "/home/denis/.dotfiles/tmux.conf" "/home/denis/.tmux.conf"
handle_file_ln "/home/denis/.dotfiles/vimperatorrc" "/home/denis/.vimperatorrc"
handle_file_ln "/home/denis/.dotfiles/vimrc" "/home/denis/.vimrc"
handle_file_ln "/home/denis/.dotfiles/xbindkeysrc" "/home/denis/.xbindkeysrc"
handle_file_ln "/home/denis/.dotfiles/xinitrc" "/home/denis/.xinitrc"
handle_file_ln "/home/denis/.dotfiles/Xressources" "/home/denis/.Xressources"
handle_file_ln "/home/denis/.dotfiles/xserverrc" "/home/denis/.xserverrc"
